# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source ‘http://github.com/CocoaPods/Specs.git'

target '点点Chat' do
platform :ios, ‘7.0’
pod ‘AMap2DMap’
pod ‘AMapSearch’
pod ‘JVFloatingDrawer’
end
